run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/Norgate-AV/vtpc
          - github.com/spf13/cobra
          - github.com/stretchr/testify
          - gopkg.in/natefinch/lumberjack.v2
          - github.com/fatih/color
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: false
  funlen:
    lines: 120
    statements: 60
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Norgate-AV/vtpc)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      # - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      # - octalLiteral
      # - whyNoLint
      - wrapperFunc
      - commentedOutCode # Allow commented code in Windows API
      # - paramTypeCombine # Allow explicit parameter types for clarity
      # - unnamedResult # Common in Windows callbacks
      # - nestingReduce # Event-driven code has natural nesting
      - equalFold # Opinionated style preference
      - hugeParam # slog.Record is 288 bytes, passing by value is idiomatic
  gocyclo:
    min-complexity: 35 # Increased for event-driven code
  goimports:
    local-prefixes: github.com/Norgate-AV/vtpc
  golint:
    min-confidence: 0
  mnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: [] # Disable - Windows API uses many constants
        ignored-functions:
          - "make"
          - "time.Sleep"
          - "time.NewTimer"
  govet:
    disable:
      - shadow # Disable shadow checking
  lll:
    line-length: 150
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "disableStutteringCheck"
      - name: package-comments
        severity: warning
        disabled: false
      - name: unused-parameter
        severity: warning
        disabled: true # Disabled - common in Windows callbacks
      - name: empty-block
        severity: warning
        disabled: true # Disabled - error checks with intentional no-ops
  maligned:
    suggest-new: true
  misspell:
    locale: US
  staticcheck:
    checks: ["all", "-SA9003"] # Disable empty branch check
  stylecheck:
    checks: ["all", "-ST1003", "-ST1020", "-ST1021"] # Disable ID naming, comment format checks
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unused
    - whitespace

  # don't enable:
  # - asciicheck
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - revive
  # - wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - mnd
        - funlen
        - gocyclo
        - dupl

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    # Exclude known linters from partially hard-to-fix issues
    - linters:
        - lll
      source: "^//go:generate "

    # Windows API specific exclusions - unsafe pointers are required
    - path: internal/windows/
      linters:
        - gosec
        - dogsled
        - revive
        - stylecheck
        - unconvert
      text: "(G103|var-naming|ALL_CAPS|underscores|package-comments|exported|unused-parameter|ST1000|ST1003)"

    # vtpro package - Windows API calls
    - path: internal/vtpro/
      linters:
        - gosec
        - gocritic
        - revive
      text: "(G103|unnamedResult|exported|stutters)"

    # Allow init functions where needed
    - linters:
        - gochecknoinits
      path: cmd/

    # Testutil mocks don't need exhaustive comments
    - path: internal/testutil/
      linters:
        - revive
        - gocritic
        - unparam
      text: "(exported.*should have comment|exported.*should be of the form|unused-parameter|unnamedResult)"

    # Logger package - allow exhaustive switch
    - path: internal/logger/
      linters:
        - exhaustive
        - revive
      text: "(missing cases|stutters|exported)"

    # Allow specific unparam in cmd
    - path: cmd/root.go
      linters:
        - unparam
      text: "result 0"

    # Allow long event handler function
    - path: internal/compiler/compiler.go
      linters:
        - funlen
      text: "handleCompilationEvents"

  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # The default value is false. If set to true exclude and exclude-rules
  # regular expressions become case sensitive.
  exclude-case-sensitive: false

  # The list of ids of default excludes to include or disable. By default it's empty.
  include:
    - EXC0002 # disable excluding of issues about comments from golint

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, e.g. if you have a multiline trailing comment
  # then enable this option and the linter will only report issues from new commits
  new: false

  # Fix found issues (if it's supported by the linter)
  fix: false
